### PR TITLE
Update Code Style: to Swift3.

### PR DESCRIPTION
**Pull request by rockerhx**

### CODE REVIEW

**Comment by googollee** [comment]
Could you remove tailing spaces?

**Comment by rockerhx** [comment]
tailing  spaces?

**Comment by googollee** [comment]
https://github.com/googollee/eviltransform/pull/46/files#diff-53ce92c758ee3bc2acf7ce02cf98144aR9

Like this line, it has some spaces in the end. Please remove all unnecessary spaces.

**Comment by rockerhx** [comment]
The spaces is Xcode and Swift code style, remove it, r u sure?

**Comment by googollee** [comment]
Thanks

**Pull request merged**
