### PR TITLE
Cut off redundancy in README, document BD funcs

### PR DESCRIPTION
**Pull request by Arthur2e5**
看上去放两张一样的表很蠢，所以干脆……全都合并了吧！

### CODE REVIEW

**Comment by Arthur2e5** [comment]
Now what should I do to the JavaScript README… There is no `#include` in plain markdown…

**Comment by Arthur2e5** [comment]
Added a stripped-down version to JS…

**Comment by googollee** [comment]
Why you changed README? Any reason?

**Comment by Arthur2e5** [comment]
1. I am bored
2. You did not document Baidu
3. Documenting Baidu in the old way equals to writing a lot of duplicate madness, so why not show how we name the whole thing?

**Pull request closed without merging**
